#!/bin/bash

set -e

#echo "Setting Defaults"

echo "Generating secrets"
safe \
  gen "${VAULT_PREFIX}/rdpg/mc/db/admin"  password -- \
  gen "${VAULT_PREFIX}/rdpg/mc/api/admin" password -- \
  gen "${VAULT_PREFIX}/rdpg/mc/sb/admin"  password -- \
  gen "${VAULT_PREFIX}/rdpg/sc/db/admin"  password -- \
  gen "${VAULT_PREFIX}/rdpg/sc/api/admin" password -- \
  >/dev/null
